variable "public_ip_name" {}
variable "location" {}
variable "resource_group_name" {}
variable "lb_name" {}
variable "backend_address_pool_name" {}
variable "probe_name" {}
variable "probe_request_path" {}
variable "probe_port" {}
variable "lb_rule_name" {}
variable "frontend_port" {}
variable "backend_port" {}